/**
 * List of available function names and params for the vibe prompt.
 * Mirrors the editor's game + std libraries (no runtime dependency).
 */
export const AVAILABLE_FUNCTIONS: { fullName: string; params: string[]; displayName?: string; hint?: string }[] = [
	{ fullName: 'vec::create', params: ['x', 'y'] },
	{ fullName: 'vec::x', params: ['v'] },
	{ fullName: 'vec::y', params: ['v'] },
	{ fullName: 'vec::add', params: ['a', 'b'] },
	{ fullName: 'vec::subtract', params: ['a', 'b'] },
	{ fullName: 'vec::scale', params: ['v', 's'] },
	{ fullName: 'vec::length', params: ['v'] },
	{ fullName: 'vec::normalize', params: ['v'] },
	{ fullName: 'vec::distance', params: ['a', 'b'] },
	{ fullName: 'std::math::add', params: ['a', 'b'] },
	{ fullName: 'std::math::subtract', params: ['a', 'b'] },
	{ fullName: 'std::math::multiply', params: ['a', 'b'] },
	{ fullName: 'std::math::divide', params: ['a', 'b'] },
	{ fullName: 'std::math::min', params: ['a', 'b'] },
	{ fullName: 'std::math::max', params: ['a', 'b'] },
	{ fullName: 'std::cmp::gt', params: ['a', 'b'] },
	{ fullName: 'std::cmp::lt', params: ['a', 'b'] },
	{ fullName: 'std::cmp::gte', params: ['a', 'b'] },
	{ fullName: 'std::cmp::lte', params: ['a', 'b'] },
	{ fullName: 'std::cmp::eq', params: ['a', 'b'] },
	{ fullName: 'std::cmp::neq', params: ['a', 'b'] },
	{ fullName: 'std::logic::and', params: ['a', 'b'] },
	{ fullName: 'std::logic::or', params: ['a', 'b'] },
	{ fullName: 'std::logic::not', params: ['a'] },
	{ fullName: 'list::empty', params: [] },
	{ fullName: 'list::cons', params: ['head', 'tail'] },
	{ fullName: 'list::head', params: ['list'] },
	{ fullName: 'list::tail', params: ['list'] },
	{ fullName: 'list::isEmpty', params: ['list'] },
	{ fullName: 'list::length', params: ['list'] },
	{ fullName: 'list::fromArray', params: ['arr'] },
	{ fullName: 'list::map', params: ['list', 'f'] },
	{ fullName: 'list::filter', params: ['list', 'pred'] },
	{ fullName: 'list::fold', params: ['list', 'init', 'f'] },
	{ fullName: 'list::forEach', params: ['list', 'f'] },
	{ fullName: 'list::minBy', params: ['list', 'f'], hint: 'list: List<EntityId>, f: lambda(eid)→number — returns the element with the SMALLEST f(e) value (e.g. lowest HP enemy)' },
	{ fullName: 'list::maxBy', params: ['list', 'f'], hint: 'list: List<EntityId>, f: lambda(eid)→number — returns the element with the LARGEST f(e) value (e.g. highest HP enemy)' },
	{ fullName: 'game::getPlayer', params: ['state'], displayName: 'getPlayer', hint: 'state: GameState → EntityId (the player)' },
	{ fullName: 'game::getEntityPosition', params: ['state', 'entity'], displayName: 'getEntityPosition', hint: 'state: GameState, entity: EntityId → Vec2 (position)' },
	{ fullName: 'game::getEntityHealth', params: ['state', 'entity'], displayName: 'getEntityHealth', hint: 'state: GameState, entity: EntityId → number (current HP)' },
	{ fullName: 'game::getNearbyEnemies', params: ['state', 'position', 'radius'], displayName: 'getNearbyEnemies', hint: 'state: GameState, position: Vec2, radius: number → List<EntityId>' },
	{ fullName: 'game::getAllEnemies', params: ['state'], displayName: 'getAllEnemies', hint: 'state: GameState → List<EntityId> (all enemies)' },
	{ fullName: 'game::damageEntity', params: ['state', 'entity', 'amount'], displayName: 'damageEntity', hint: 'state: GameState, entity: EntityId (use head/tail of enemy list), amount: number (damage value, use a literal) → deals damage' },
	{ fullName: 'game::spawnFireball', params: ['state', 'position', 'direction'], displayName: 'spawnFireball', hint: 'state: GameState, position: Vec2, direction: Vec2 → spawns a fireball' },
	{ fullName: 'game::healEntity', params: ['state', 'entity', 'amount'], displayName: 'healEntity', hint: 'state: GameState, entity: EntityId, amount: number (heal value) → heals entity' },
	{ fullName: 'game::teleportRelative', params: ['state', 'entity', 'delta'], displayName: 'teleportRelative', hint: 'state: GameState, entity: EntityId, delta: Vec2 → teleports entity' },
	{ fullName: 'game::emitEvent', params: ['state', 'eventName'], displayName: 'emitEvent', hint: 'state: GameState, eventName: string → emits a game event' },
	{ fullName: 'game::setTimeout', params: ['state', 'delayMs', 'callback'], displayName: 'setTimeout', hint: 'state: GameState, delayMs: number, callback: function → delayed callback' },
];
